Revert "chore: remove index"
MauricioRobayo/eleventy-blog pull request #51
Opened 2021-07-22 01:14 UTC by MauricioRobayo

2021-08-02 00:04 UTC, oscarnava requested changes
Thanks, @MauricioRobayo.

I left you some comments. How about you take a look at them, apply the suggested changes and I take a new look after you do? 🙂 

Good job BTW! 💪

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +    <script>
First of all, I would discourage you from including the script code in the HTML. It's not a good practice… in fact, is a bad practice. The same with the CSS. Always separate those three (at least) into separated files and include them in the HTML.

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +              element.textContent = loaderSymbols[++i % loaderSymbols.length];
Although it's perfectly valid, using `++i` around the code is difficult to catch and easy to oversee. It's better if you are more explicit when changing the value of a variable. Even more, when using `++i` and `i++` you risk introducing subtle bugs. In short, there's a difference between _**can use it**_ and _**should use it**_.
Also, `i` is a really bad name. 😕 
```suggestion
              i += 1;
              element.textContent = loaderSymbols[i % loaderSymbols.length];
```

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +      }
I think it's better if you use the `Class` syntax. It's easier to read and a bit less obscure than having a function create your object instances. Also, the way you are using the closures is smart but can be tricky to maintain. If you like, you can use private properties. 
```suggestion
      class Loader {
        #interval;
        #step;

        constructor() {
          this.element = document.createElement("span");
          this.element.classList.add("repo-loader");
          this.#interval = null;
          this.#step = 0;
        }

        start() {
            const loaderSymbols = ["\\", "|", "/", "—"];
            this.element.textContent = loaderSymbols[this.#step % loaderSymbols.length];
            this.#interval = setInterval(() => {
              console.log("ticking");
              this.#step += 1;
              element.textContent = loaderSymbols[this.#step % loaderSymbols.length];
            }, 500);
        }

        stop(textContent = "") {
          clearInterval(this.#interval);
          this.element.textContent = textContent;
        }
      }
```

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +        loader: createLoader(),
If using the class syntax, just replace this line:
```suggestion
        loader: new Loader(),
```

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +        const data = await fetchRepos({
I would discourage you from using `async/await` since those are blocking operations; use `Promises` instead.

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +      function createCache(key) {
This function is also a good candidate for a `Class` definition. Why don't you take a shot and redefine it?

2021-08-02 00:04 UTC, oscarnava commented on index.html
> +            if (cache?.expirationTime > Date.now()) {
Why using the existential operator here? As far as I can see, the `expirationTime` property would be defined always.
```suggestion
            if (cache.expirationTime > Date.now()) {
```

2021-08-05 01:31 UTC, MauricioRobayo commented on index.html
> +            if (cache?.expirationTime > Date.now()) {
Great observation! The issue is that `cache` is null if you open the page for the first time, and trying to access a property on null throws an error (`cannot read property 'expirationTime' of null). That's why it is needed.

2021-08-05 01:41 UTC, MauricioRobayo commented on index.html
> +      function createCache(key) {
I gave this some thought and decided to use factory functions and closures to keep them fresh in my mind, and the use case is so simple and straightforward that somehow I felt a class was an overkill, but I agree, this is more readable and user friendly with classes. Thanks!

2021-08-05 01:42 UTC, MauricioRobayo commented on index.html
> +      }
Awesome, thanks, definitely cleaner with classes.

2021-08-05 01:51 UTC, MauricioRobayo commented on index.html
> +        const data = await fetchRepos({
I thought `asycn/await` was syntactic sugar over `Promises` 🤔, and that it was non-blocking. Both requests happen in parallel, not sequentially. Do you have any resources so I can dig a little bit more into understanding this?

2021-08-05 02:14 UTC, MauricioRobayo commented on index.html
> +    <script>
Could you expand on this... it is not clear to me why is it bad practice in this particular use case?

What would be the advantages and disadvantages of each approach in this particular use case so we can balance which is the best approach in this context?

2021-08-05 02:29 UTC, MauricioRobayo commented on index.html
> +              element.textContent = loaderSymbols[++i % loaderSymbols.length];
Agree, thanks!

2021-08-08 20:56 UTC, oscarnava reviewed
Some more comments. 🙂

2021-08-08 20:56 UTC, oscarnava commented on index.html
> +        const data = await fetchRepos({
I stand corrected. After a bit of fiddling with your code I can see JS is not behaving like other languages `await` equivalent. I can see that more than an "**_await_**" it's more like "**_go do something else and I'll let you know when I'm finished_**". I guess it's a consequence of the single-threaded nature of JS. The name is a bit misleading but now I understand better the behavior and I can see I had some bad preconceptions about it. It was an interesting experiment, and I learned something important today, thanks! 🙂

2021-08-08 20:56 UTC, oscarnava commented on index.html
> +      }) {
Something I love from the OOP is that you can join data and functions in one contained entity. I would suggest you define the `Project` class and move all related functionality there, something like this:

```javascript
class Project {
  constructor(containerId, sort, metaFields, limit = 3) {
    this.container = document.getElementById(containerId);
    this.sort = sort;
    this.metaFields = metaFields;
    this.limit = limit;
    this.loader = new Loader();
  }

  async load() {
    const url = `https://api.github.com/search/repositories?q=user:MauricioRobayo&sort=${this.sort}&per_page=${this.limit}`;
    const header = createHeader(url, this.loader);
    this.container.append(header);

    this.loader.start();

    const data = await fetchRepos({
      url,
      cache: new Cache(`${this.sort}-${this.limit}`),
    });

    if (data.error) {
      this.loader.stop("✗");

      this.container.classList.add("error");
      this.container.append(data.message);
    } else {
      this.loader.stop("✔");

      if (data.cacheHit) {
        const cacheStatus = createCacheStatus(data.expirationTime);
        header.append(cacheStatus);
      } else {
        const rateLimit = createRateLimit(data.rateLimit);
        header.append(...rateLimit);
      }

      const body = createBody();
      const repos = createRepos({
        container: body,
        repos: data.repos,
        metaFields: this.metaFields
      });
      body.append(...repos);
      this.container.append(body);
    }
  }
}
```

…and then just create the projects like this:

```javascript
new Project("recent-projects", "updated", ["language", "updated_at"])
  .load()

new Project("starred-projects", "stars", ["language", "stargazers_count"])
  .load()
```

For me it's much more easy to organize and control. You can even have one class per file and organize even better your code. I bet you can improve this definition furthermore by moving other functions inside this class. 🙂

2021-08-08 20:56 UTC, oscarnava commented on index.html
> +      function createRepos({ container, repos, metaFields }) {
The parameter `container` is not used here. Is that expected, or a bug? 🤔 
```suggestion
      function createRepos({ repos, metaFields }) {
```

2021-08-08 20:56 UTC, oscarnava commented on index.html
> +    <script>
My suggestion would be something [like this](https://github.com/MauricioRobayo/mauriciorobayo.github.io/tree/split-code). I would even go further and place each file into a special folder (`/js` for javascript, `/css` for styles).

- Advantages of splitting:
  - In short, [separation of concerns.](https://www.castsoftware.com/blog/how-to-implement-design-pattern-separation-of-concerns)
  - Better control of code.
  - Painless growth.
  - Specially with CSS, you can change the style of your webpage in a blink of an eye.
  - Looks better in a resume.

- Disadvantages of splitting:
  - Maybe too overkill for very small projects.

- Advantages of one-file-fits-all:
  - When you need for some reason to integrate all in one, like for example to embed HTML/CSS/JS code into an Android App to show a help screen using a WebView.
  - A dead simple web page.

- Disadvantages of one-file-fits-all:
  - Looks amateurish. 
  - If you want to showcase your developer abilities, don't do it like this. If I were evaluating you for some developer position, this would cost you a lot of points.
  - Makes it difficult to navigate and understand the code.
  - Working in a team, you need to make sure your code is as readable as possible.

[What are advantages of using CSS? Why we need to separate CSS from HTML?](https://developer-interview.com/p/html-css/what-are-advantages-of-using-css-why-we-need-to-separate-css-from-html-26)
[What is better. Having html, css, JavaScript in the same file or in separate file?](https://www.quora.com/What-is-better-Having-html-css-JavaScript-in-the-same-file-or-in-separate-file)

2021-08-10 19:58 UTC, MauricioRobayo commented on index.html
> +      }) {
@oscarnava I love this, thanks, I messed around a little bit with this and splitting the code into modules, I think this greatly helps improve the code. Thanks!

2021-10-27 11:41 UTC, closed without merging